# Generated by Django 5.0.6 on 2025-10-07 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0002_alter_answer_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='content',
        ),
        migrations.AddField(
            model_name='answer',
            name='justify_alternative',
            field=models.TextField(blank=True, null=True),
        ),
    ]
